trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: FlutterInstall@0
    inputs:
      channel: 'stable'
      version: 'latest'

  - task: FlutterBuild@0
    inputs:
      target: 'apk'
      projectDirectory: '.'
