trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
  - task: FlutterInstall@0
    displayName: 'Install Flutter SDK'
    inputs:
      channel: 'stable'
      version: 'latest'

  - task: FlutterBuild@0
    displayName: 'Build application'
    inputs:
      target: 'apk'
      projectDirectory: '.'
