trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
  - task: UseJava@0
    inputs:
      version: '11'
      jdkArchitecture: 'x64'
  - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'latest'
  - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
    displayName: 'Build application'
    inputs:
      target: 'apk'
      projectDirectory: './task_manager'