trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
  - task: FlutterInstall@0
    displayName: 'Install Flutter'
    inputs:
      channel: 'stable'
      version: 'latest'
  - script: |
      flutter upgrade
    displayName: 'Upgrade Flutter'
  - task: FlutterBuild@0
    displayName: 'Build application'
    inputs:
      target: 'apk'
      projectDirectory: './task_manager'
