trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'latest'
  - task: FlutterBuild@0
    displayName: 'Build application'
    inputs:
      target: 'apk'
      projectDirectory: './task_manager'
